#!/usr/bin/env bash
# Generate docker-compose.yml from .env. CLUSTER_SIZE controls how many
# node services are emitted; node0 is always the init node.
#
# The ACCEPT_FAIL / PROPOSE_FAIL placeholders are emitted as literal
# ${ACCEPT_FAIL} / ${PROPOSE_FAIL} so docker compose itself substitutes
# them at runtime against .env (matching the failure-rate knobs).
#
# Usage: bash scripts/gen-compose.sh > docker-compose.yml
#        (or just `make docker-build`, which runs this for you)

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
    # shellcheck disable=SC1091
    . ./.env
fi
: "${CLUSTER_SIZE:=5}"

if ! [[ "$CLUSTER_SIZE" =~ ^[0-9]+$ ]] || [ "$CLUSTER_SIZE" -lt 1 ]; then
    echo "gen-compose: CLUSTER_SIZE must be a positive integer (got '$CLUSTER_SIZE')" >&2
    exit 1
fi

cat <<'HEADER'
# Generated by scripts/gen-compose.sh from .env. Do not edit directly.
# Re-run `make docker-build` (or scripts/gen-compose.sh > docker-compose.yml)
# after editing .env.

services:
  node0:
    image: paxos-kvstore:latest
    build: .
    hostname: node0
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.rmi.server.hostname=node0"
      ACCEPT_FAIL: "${ACCEPT_FAIL}"
      PROPOSE_FAIL: "${PROPOSE_FAIL}"
    command: ["0", "node0", "1099", "node0", "1099", "--init"]
    networks: [paxos_net]
    stop_grace_period: 3s
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/1099 && exec 3<&-"]
      interval: 1s
      timeout: 2s
      retries: 30
      start_period: 2s
HEADER

i=1
while [ "$i" -lt "$CLUSTER_SIZE" ]; do
    cat <<JOINER

  node$i:
    image: paxos-kvstore:latest
    build: .
    hostname: node$i
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.rmi.server.hostname=node$i"
      ACCEPT_FAIL: "\${ACCEPT_FAIL}"
      PROPOSE_FAIL: "\${PROPOSE_FAIL}"
    command: ["$i", "node$i", "1099", "node0", "1099"]
    networks: [paxos_net]
    stop_grace_period: 3s
    depends_on:
      node0:
        condition: service_healthy
JOINER
    i=$((i + 1))
done

cat <<'FOOTER'

networks:
  paxos_net:
    driver: bridge
FOOTER
