#!/usr/bin/env bash
# Generate docker-compose.<CLUSTER_NAME>.yml from .env. CLUSTER_SIZE controls how
# many node services are emitted; node0 is always the init node. CLUSTER_NAME
# namespaces the host log volumes (logs/<name>/node#), is exported to each node
# via the CLUSTER_NAME env var, and is used by callers as the docker compose
# project name (-p) so multiple named clusters stay isolated.
#
# The ACCEPT_FAIL / PROPOSE_FAIL / MSG_LOSS placeholders are emitted as literal
# ${ACCEPT_FAIL} / ${PROPOSE_FAIL} / ${MSG_LOSS} so docker compose itself
# substitutes them at runtime against .env (matching the failure-rate knobs).
#
# Usage: CLUSTER_NAME=foo bash scripts/gen-compose.sh > docker-compose.foo.yml

set -euo pipefail

cd "$(dirname "$0")/.."

_CLUSTER_SIZE_OVERRIDE="${CLUSTER_SIZE:-}"
_CLUSTER_NAME_OVERRIDE="${CLUSTER_NAME:-}"

if [ -f .env ]; then
    # shellcheck disable=SC1091
    . ./.env
fi

CLUSTER_SIZE="${_CLUSTER_SIZE_OVERRIDE:-${CLUSTER_SIZE:-5}}"
CLUSTER_NAME="${_CLUSTER_NAME_OVERRIDE:-${CLUSTER_NAME:-default}}"

if ! [[ "$CLUSTER_SIZE" =~ ^[0-9]+$ ]] || [ "$CLUSTER_SIZE" -lt 1 ]; then
    echo "gen-compose: CLUSTER_SIZE must be a positive integer (got '$CLUSTER_SIZE')" >&2
    exit 1
fi

if ! [[ "$CLUSTER_NAME" =~ ^[a-z0-9][a-z0-9_-]*$ ]]; then
    echo "gen-compose: CLUSTER_NAME must match ^[a-z0-9][a-z0-9_-]*\$ (got '$CLUSTER_NAME')" >&2
    exit 1
fi

cat <<HEADER
# Generated by scripts/gen-compose.sh from .env. Do not edit directly.
# Re-run scripts/gen-compose.sh > docker-compose.${CLUSTER_NAME}.yml after editing .env.

services:
  node0:
    image: paxos-kvstore:latest
    build: .
    hostname: node0
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.rmi.server.hostname=node0"
      ACCEPT_FAIL: "\${ACCEPT_FAIL}"
      PROPOSE_FAIL: "\${PROPOSE_FAIL}"
      MSG_LOSS: "\${MSG_LOSS}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      LOG_DIR: "/app/logs/${CLUSTER_NAME}/node0"
    command: ["0", "node0", "1099", "node0", "1099", "--init"]
    networks: [paxos_net]
    volumes:
      - ./logs/${CLUSTER_NAME}/node0:/app/logs/${CLUSTER_NAME}/node0
    stop_grace_period: 3s
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/1099 && exec 3<&-"]
      interval: 1s
      timeout: 2s
      retries: 30
      start_period: 2s
HEADER

i=1
while [ "$i" -lt "$CLUSTER_SIZE" ]; do
    cat <<JOINER

  node$i:
    image: paxos-kvstore:latest
    build: .
    hostname: node$i
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.rmi.server.hostname=node$i"
      ACCEPT_FAIL: "\${ACCEPT_FAIL}"
      PROPOSE_FAIL: "\${PROPOSE_FAIL}"
      MSG_LOSS: "\${MSG_LOSS}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      LOG_DIR: "/app/logs/${CLUSTER_NAME}/node$i"
    command: ["$i", "node$i", "1099", "node0", "1099"]
    networks: [paxos_net]
    volumes:
      - ./logs/${CLUSTER_NAME}/node$i:/app/logs/${CLUSTER_NAME}/node$i
    stop_grace_period: 3s
    depends_on:
      node0:
        condition: service_healthy
JOINER
    i=$((i + 1))
done

cat <<'FOOTER'

networks:
  paxos_net:
    driver: bridge
FOOTER
